In [1]:
import numpy as np
np.random.seed(3)
A = np.random.randint(0,100,size=(9,9))
print("Initial Matrix")
print(A)
B = []
C = np.zeros((A.shape[0], A.shape[1]))
for row in range(A.shape[0]):
  mean = (A[row,:]).mean()
  B.append(mean)

zerosCount = 0
nonZerosCount = 0

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if B[i] < A[i,j]:
            C[i,j] = 0
            zerosCount = zerosCount+1
        else:
            C[i,j] = A[i,j]
            nonZerosCount = nonZerosCount+1

print("Number of zeros: ",zerosCount)
print("Number of non-zeros: ",nonZerosCount)

if(nonZerosCount+zerosCount == A.size):
    print("Updated Matrix is verified")

print("Updated Matrix")
print(C)

Initial Matrix
[[24  3 56 72  0 21 19 74 41]
 [10 21 38 96 20 44 93 39 14]
 [26 81 90 22 66  2 63 60  1]
 [51 90 69 97 29 24 62  7 43]
 [33 79 48 37 20 94 49 21 78]
 [28 54  0 64 18 63 37 56 56]
 [71 37 46 33  1 85 74 99 91]
 [16 80 32 16 18 75 55 96 95]
 [13 37 30 48 61 33 52  2 28]]
Number of zeros:  38
Number of non-zeros:  43
Updated Matrix is verified
Updated Matrix
[[24.  3.  0.  0.  0. 21. 19.  0.  0.]
 [10. 21. 38.  0. 20.  0.  0. 39. 14.]
 [26.  0.  0. 22.  0.  2.  0.  0.  1.]
 [51.  0.  0.  0. 29. 24.  0.  7. 43.]
 [33.  0. 48. 37. 20.  0. 49. 21.  0.]
 [28.  0.  0.  0. 18.  0. 37.  0.  0.]
 [ 0. 37. 46. 33.  1.  0.  0.  0.  0.]
 [16.  0. 32. 16. 18.  0.  0.  0.  0.]
 [13.  0. 30.  0.  0. 33.  0.  2. 28.]]
